### ISSUE TITLE
tzx tools tuple error

### ISSUE THREAD

**Issue by IcePee** [shred/tzxtools#1]
Hello,

When running any command, I get:
Traceback (most recent call last):
  File "tzxls", line 42, in <module>
    tzx.read(f)
  File "tzxtools/tzxlib/tzxfile.py", line 42, in read
    block.read(tzx)
  File "tzxtools/tzxlib/tzxblocks.py", line 324, in read
    self.data += tzx.read(len)
TypeError: integer argument expected, got 'tuple'

**Comment by shred** [comment]
Hmmm... It's still working for me. Can you give me the python version you are using?

**Comment by shred** [comment]
Please ignore my last question. I think I found the error...

**Comment by shred** [comment]
Can you try again?

**Comment by IcePee** [comment]
That looks like it's worked!
