### ISSUE TITLE
Convert all files in a directory using tzxtap

### ISSUE THREAD

**Issue by lackovic** [shred/tzxtools#14]
How do I use `tzxtap` to convert all `TZX` files in a directory to `TAP` files, keeping their name and changing the extension to `TAP`?

If it's not possible, would you consider adding this functionality?

**Comment by shred** [comment]
This can be simply done using the shell. For example, on Linux and bash, you can convert all files in a directory like this:

```sh
for file in *.tzx; do
  echo "$file"
  tzxtap --to "${file%.tzx}.tap" "$file"
done
```

If you need recursive conversion, you can do something similar with `find` instead of `for`.

**Comment by lackovic** [comment]
What's the `-t` argument for? I can't find it in [the docs](https://shredzone.org/docs/tzxtools/tzxtap/).
