### ISSUE TITLE
Feature request: Add info of time in milliseconds in audio file where crc errored block is present

### ISSUE THREAD

**Issue by wadim-al** [shred/tzxtools#6]
Hello!
Feature request:
Add debug output of a millisecond where CRC errored block is found in the source wav file, so I can manually edit the broken audio sample to possibly recover the data

Nevermind, debug shows the sample number which is better than a millisecond.

**Comment by shred** [comment]
Yes, the sample number is better, and can also be used in tools like Audacity.

But you still made a good point. The sample numbers should not be buried in the debug output, but should be shown in the verbose output, so it is easier to spot the position of a CRC error.

**Comment by shred** [comment]
The starting and ending sample numbers are now shown on `--verbose`. It's released in v1.4.0. Thank you for the inspiration!

**Comment by wadim-al** [comment]
Thanks for implementing so quick!
